dist: trusty

sudo: required

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.0.1

env:  
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true

script:
  - dotnet --info
  - dotnet restore src/SimMetrics.Net/SimMetrics.Net.csproj
  - dotnet build src/SimMetrics.Net/SimMetrics.Net.csproj --configuration Release --framework netstandard1.0

  - dotnet restore tests/SimMetrics.Net/SimMetrics.Net.Tests.csproj
  - dotnet test tests/SimMetrics.Net.Test/SimMetrics.Net.Test.csproj --configuration Release --framework net452
