dist: trusty

sudo: required

language: csharp

mono: latest
dotnet: 1.0.1

script:
# SRC : Restore and Build
- dotnet restore src/SimMetrics.Net

- dotnet build src/SimMetrics.Net --configuration Release --framework netstandard1.0

- export FrameworkPathOverride=/usr/lib/mono/2.0-api
- dotnet build src/SimMetrics.Net --configuration Release --framework net20
- dotnet build src/SimMetrics.Net --configuration Release --framework net35

- export FrameworkPathOverride=/usr/lib/mono/4.0-api
- dotnet build src/SimMetrics.Net --configuration Release --framework net40

- export FrameworkPathOverride=/usr/lib/mono/4.5
- dotnet build src/SimMetrics.Net --configuration Release --framework net45

# TEST : Restore and Build
- dotnet restore tests/SimMetrics.Net.Tests

- export FrameworkPathOverride=/usr/lib/mono/4.5
- dotnet build tests/SimMetrics.Net.Tests --configuration Release --framework net45
