dist: trusty

sudo: required

language: csharp

mono: latest
dotnet: 1.0.1

env:  
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true

script:
  - dotnet --info
  - dotnet restore src/SimMetrics.Net
  - dotnet build src/SimMetrics.Net --framework netstandard1.0
  - xbuild /p:Configuration=Release build src/SimMetrics.Net