version: 1.0.2.{build}

configuration:
- Release

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

environment:
  COVERALLS_REPO_TOKEN:
    secure: GhxjOYPfvNvUp7RhT6bud8pA9GWYrGd3KV+G/JFlxRtg2t2F3fCY3tgsq2jwDubE

install:
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1" -OutFile ".\dotnet-install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\dotnet-install.ps1 -InstallDir "$env:DOTNET_INSTALL_DIR" -Version 1.0.1 -NoPath'
  - ps: $env:PATH = "$env:DOTNET_INSTALL_DIR;$env:PATH"
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"

build_script:
  - cmd: dotnet --info

  # Restore and build 'src'
  - cmd: dotnet restore src\SimMetrics.Net\SimMetrics.Net.csproj
  - cmd: run --project src\SimMetrics.Net\SimMetrics.Net.csproj --configuration %CONFIGURATION%

  # Restore and build 'tests'
  - cmd: dotnet restore tests\SimMetrics.Net\SimMetrics.Net.Tests.csproj
  - cmd: dotnet build tests\SimMetrics.Net\SimMetrics.Net.Tests.csproj --configuration %CONFIGURATION%

test_script:
  - cmd: dotnet test tests\SimMetrics.Net.Tests\SimMetrics.Net.Tests.csproj --configuration %CONFIGURATION%

after_test:
  - nuget.exe install OpenCover -ExcludeVersion
  - nuget.exe install coveralls.net -ExcludeVersion
  - OpenCover\tools\OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:"\".\tests\SimMetrics.Net.Tests\bin\%CONFIGURATION%\net452\win7-x64\SimMetrics.Net.Tests.dll\" --result=myresults.xml;format=AppVeyor" -returntargetcode -filter:"+[SimMetrics.Net]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
  - coveralls.net\tools\csmacnz.Coveralls.exe --opencover -i .\coverage.xml

artifacts:
- path: 'source\**\*.nupkg'

cache:
- packages