version: 1.0.5.{build}

configuration:
- Debug

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

environment:
  COVERALLS_REPO_TOKEN:
    secure: GhxjOYPfvNvUp7RhT6bud8pA9GWYrGd3KV+G/JFlxRtg2t2F3fCY3tgsq2jwDubE

install:
  - ps: Start-FileDownload 'https://download.microsoft.com/download/8/8/5/88544F33-836A-49A5-8B67-451C24709A8F/dotnet-sdk-2.1.300-win-x64.exe'
  - cmd: dotnet-sdk-2.1.300-win-x64.exe /quiet
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"

build_script:
  - cmd: dotnet --info

  # Restore and build 'src'
  - cmd: dotnet restore src\SimMetrics.Net\SimMetrics.Net.csproj
  - cmd: dotnet build src\SimMetrics.Net\SimMetrics.Net.csproj --configuration %CONFIGURATION% --framework netstandard1.0

  # Restore and build 'tests'
  - cmd: dotnet restore tests\SimMetrics.Net.Tests\SimMetrics.Net.Tests.csproj
  - cmd: dotnet build tests\SimMetrics.Net.Tests\SimMetrics.Net.Tests.csproj --configuration %CONFIGURATION% --framework netcoreapp1.1

test_script:
  - cmd: dotnet test tests\SimMetrics.Net.Tests\SimMetrics.Net.Tests.csproj --configuration %CONFIGURATION% --framework netcoreapp1.1

after_test:
  - nuget.exe install OpenCover -ExcludeVersion
  - nuget.exe install coveralls.net -ExcludeVersion -Version 0.7.0
  - pip install codecov

  - cmd: '"OpenCover\tools\OpenCover.Console.exe" -target:dotnet.exe -targetargs:"test tests\SimMetrics.Net.Tests\SimMetrics.Net.Tests.csproj --configuration %CONFIGURATION%  --no-build" -output:coverage.xml -register:user -filter:"+[SimMetrics.Net]* -[SimMetrics.Net.Tests]*" -returntargetcode -register:user -oldstyle'
  - codecov -f "coverage.xml"
  - coveralls.net\tools\csmacnz.Coveralls.exe --opencover -i .\coverage.xml