version: 1.0.2.{build}

configuration:
- Release

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

environment:
  COVERALLS_REPO_TOKEN:
    secure: GhxjOYPfvNvUp7RhT6bud8pA9GWYrGd3KV+G/JFlxRtg2t2F3fCY3tgsq2jwDubE

install:
  - ps: Start-FileDownload 'https://download.microsoft.com/download/8/F/9/8F9659B9-E628-4D1A-B6BF-C3004C8C954B/dotnet-1.1.1-sdk-win-x64.exe'
  - cmd: dotnet-1.1.1-sdk-win-x64.exe /quiet
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"

build_script:
  - cmd: dotnet --info

  # Restore and build 'src'
  - cmd: dotnet restore src\SimMetrics.Net\SimMetrics.Net.csproj
  - cmd: dotnet build src\SimMetrics.Net\SimMetrics.Net.csproj --configuration %CONFIGURATION% --framework netstandard1.0

  # Restore and build 'tests'
  - cmd: dotnet restore tests\SimMetrics.Net.Tests\SimMetrics.Net.Tests.csproj
  - cmd: dotnet build tests\SimMetrics.Net.Tests\SimMetrics.Net.Tests.csproj --configuration %CONFIGURATION% --framework netcoreapp1.1

test_script:
  - cmd: dotnet test tests\SimMetrics.Net.Tests\SimMetrics.Net.Tests.csproj --configuration %CONFIGURATION% --framework netcoreapp1.1

after_test:
  - nuget.exe install OpenCover -ExcludeVersion
  - nuget.exe install coveralls.net -ExcludeVersion
  - pip install codecov

  - OpenCover\tools\OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"\"test tests\SimMetrics.Net.Tests\SimMetrics.Net.Tests.csproj\" --result=myresults.xml;format=AppVeyor" -returntargetcode -filter:"+[SimMetrics.Net]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:coverage.xml

  - codecov -f "coverage.xml"
  - coveralls.net\tools\csmacnz.Coveralls.exe --opencover -i .\coverage.xml

artifacts:
- path: 'source\**\*.nupkg'

cache:
- packages