os: Visual Studio 2015

version: 1.0.0.{build}

configuration:
- Release

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe'
- cmd: dotnet-dev-win-x64.latest.exe /quiet

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\

build_script:
- appveyor-retry dotnet restore .\src\SimMetrics.Net
- dotnet build .\src\SimMetrics.Net\project.json -c %CONFIGURATION%
- dotnet pack -c Release --no-build --version-suffix %LABEL% -o .\artifacts .\src\SimMetrics.Net\project.json

- appveyor-retry dotnet restore .\tests\SimMetrics.Net.Tests
- dotnet build .\tests\SimMetrics.Net.Tests\project.json -c %CONFIGURATION%

test_script:
- dotnet test -c %CONFIGURATION% --no-build .\tests\SimMetrics.Net.Tests

after_test:
- nuget install opencover -ExcludeVersion -OutputDirectory %APPVEYOR_BUILD_FOLDER%\tools

    %APPVEYOR_BUILD_FOLDER%\tools\OpenCover\OpenCover.Console.exe-register:user -target:"nunit3-console.exe" -targetargs:"/noresults /noisolation /testcontainer:"".\tests\SimMetrics.Net.Tests\bin\Release\SimMetrics.Net.Tests.dll" -filter:"+[SimMetrics.Net]*  -[SimMetrics.Net]SimMetrics.Net.Properties.*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\coverage.xml

    C:\Python35-x64\python.exe -m pip install codecov

    C:\Python35-x64\Scripts\codecov -f coverage.xml

artifacts:
- path: artifacts\**\*.*

cache:
- packages